#Updated configuration
#Sat Jul 04 11:10:24 CST 2026
AI_MODEL=deepseek-v4-pro
CONNECT_KEEPALIVE_SECONDS=180
DEFAULT_LISTVIEW_TAB=0
RESULT_FETCH_PER_TIME=200
SPLIT_DRIVER_MAIN=0.23984375
SPLIT_DRIVER_SQL=0.6
SQL_EDITOR_FONT_SIZE=12
UI_LANG=en
UI_THEME=dark
