#Updated configuration
#Thu Mar 05 18:05:08 CST 2026
AI_API_BASE_URL=https\://api.openai.com/v1
AI_API_TOKEN=13f1f8c1-5e29-46c9-836f-db2321b3c9b6
AI_API_TOKEN_DOUBAO=13f1f8c1-5e29-46c9-836f-db2321b3c9b6
AI_PROVIDER=doubao
DEFAULT_LISTVIEW_TAB=2
RESULT_FETCH_PER_TIME=200
SPLIT_DRIVER_MAIN=0.18178264268960126
SPLIT_DRIVER_SQL=0.6
UI_LANG=zh-CN
