#Updated configuration
#Tue May 19 20:46:10 CST 2026
CONNECT_KEEPALIVE_SECONDS=180
DEFAULT_LISTVIEW_TAB=0
RESULT_FETCH_PER_TIME=200
SPLIT_DRIVER_MAIN=0.25546875
SPLIT_DRIVER_SQL=0.6
SQL_EDITOR_FONT_SIZE=12
UI_LANG=zh-CN
